language: python

python:
  - 2.7

install:
  - pip install requests markdown beautifulsoup4

script:
  - python check_urls.py free-software-testing-books-ru.md
  - python check_urls.py free-software-testing-books.md

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
