language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - awesome_bot README.md free-software-testing-courses.md free-software-testing-books.md --allow-redirect

notifications:
  email:
    recipients:
      - estetus+travis-ci@gmail.com
    on_success: change
    on_failure: always
